### ISSUE TITLE
Implement Forest Area 02 (Lake)

### ISSUE THREAD

**Issue by chmilk1** [AztecGameLab/LongTermGame7#107]
this is the lake, progress will be on james-branch
feel free to open it up, walk around, make some suggestions

**Comment by alyg563** [comment]
Make sure to reference the description in [Writing Team Descriptions](https://docs.google.com/document/d/1PAL_sZ5QMTnG_mTCcDIpI5Lab5KFGKpDHEPa15HjxrM/edit?usp=sharing)
