### ISSUE TITLE
Design the Forest Area (Deforested Area)

### ISSUE THREAD

**Issue by chmilk1** [AztecGameLab/LongTermGame7#108]
Chopped down forest (logging), corrupted

Feel Free to re design, the design is sketchy for it

Quick Mock Up: [this](https://drive.google.com/file/d/1TinolD7xgs3cUMsGW1mCBqFqdypqhfU3/view?usp=sharing)

Story Description for the area: WIP

**Comment by whatAreYouD0ingStepBr0** [comment]
![image](https://user-images.githubusercontent.com/113555708/216691564-8e9fc46f-cb03-49d1-859e-475f755a8ff2.jpeg)

**Comment by alyg563** [comment]
I like everything try looking at the story docs to add more story moments/details! Maybe pollute rivers?
