### ISSUE TITLE
Forest Area 04 (Roosting Area)

### ISSUE THREAD

**Issue by chmilk1** [AztecGameLab/LongTermGame7#109]
Roosting Area,

feel free to redesign, no plan is complete for this area
[quick mock up](https://drive.google.com/file/d/1TinolD7xgs3cUMsGW1mCBqFqdypqhfU3/view?usp=sharing)

**Comment by admlars2** [comment]
![Image](https://user-images.githubusercontent.com/110800344/216502241-071a794d-6780-4404-9986-1527e388a6b0.png)

Very Basic Initial Idea

**Comment by admlars2** [comment]
I think I am going to expand the area slightly and add some more spots for foliage. I am thinking of placing a waterfall at one of the  sides and might change the shape slightly based on what the other areas are looking like.

**Comment by alyg563** [comment]
Sweet! I will add you to that issue now! Everything looks great I definitely agree with the waterfall. Don't worry about the shape of your level because we aren't necessarily fitting them together like puzzle pieces.
