### ISSUE TITLE
Implement Forest Area 04 (Roosting Area)

### ISSUE THREAD

**Issue by chmilk1** [AztecGameLab/LongTermGame7#130]
Reference design in #109

**Comment by admlars2** [comment]
![Image](https://user-images.githubusercontent.com/110800344/218046733-fa0ca697-ea82-4969-82e7-40547e382e9c.png)

Worked on the Basic Terrain Features that I wanted to have

**Comment by admlars2** [comment]
![Image](https://user-images.githubusercontent.com/110800344/219788691-2c99df6b-4182-4331-aa9f-f16f05c29cdd.png)

Continued Work and balanced out the area more

**Comment by admlars2** [comment]
![Image](https://user-images.githubusercontent.com/110800344/219811542-4e9697aa-e5f0-4491-9979-4572ad30fdec.png)

Painted In some textures and added trees (not in render distance)
