### ISSUE TITLE
Design Hills Area 01 (Research Camp)

### ISSUE THREAD

**Issue by alyg563** [AztecGameLab/LongTermGame7#136]
Story document: https://docs.google.com/document/d/1SYlhTb3QH-6a_9kRvVhsz5wGfWOOdDdaPM-TR_qrm7w/edit?usp=sharing

**Comment by mmalongg** [comment]
![Image](https://user-images.githubusercontent.com/100890695/219799457-643f884e-759b-420e-9a92-c195f22245dd.jpg)

Brief first overview sketch of the research camp. I tried to match the story description as best as I can. The player will spawn in from the left and approach the camp that is over viewing the forest. Will make changes and improvements as it goes along.

Still need to conceptualize the inside of the tents and wagon.
