### ISSUE TITLE
Object blockouts (Lab)

### ISSUE THREAD

**Issue by alyg563** [AztecGameLab/LongTermGame7#160]
Create object blockouts for this room:

![Image](https://user-images.githubusercontent.com/43483413/221100446-a38da3d6-a7b3-46bc-9a8f-38f522eee559.png)

**Comment by whatAreYouD0ingStepBr0** [comment]
![image](https://user-images.githubusercontent.com/113555708/224413114-23a2b4aa-3613-4f8a-b03b-7f86a69362a1.png)
work in progress

**Comment by alyg563** [comment]
Thanks for the work! Bri went ahead and did these instead so they could get to the material phase quicker.
