### ISSUE TITLE
Write workflow guide for concept art

### ISSUE THREAD

**Issue by sixlegdragon** [AztecGameLab/LongTermGame7#18]
Create an illustrated document that explains the steps and expectations for each concept art item, including 

- [x] story team's description
- [x] min 3x research references
- [x] min 3x sketches
- [x] team review 
- [x] min 1x stage of iteration

**Comment by 0Arkadias0** [comment]
https://docs.google.com/document/d/1CMDsyScy-Y78eNdjovInDKc91IcBbclx4lXtwuVfmZk/edit?usp=sharing
