### ISSUE TITLE
Artichokie concept

### ISSUE THREAD

**Issue by sixlegdragon** [AztecGameLab/LongTermGame7#27]
Demonstrate the concept art process for workflow guide by showing each step on the Artichokie demo monster, including healthy and corrupted versions

- [ ] story blurb
- [x] 3x references
- [x] 3x sketches
- [x] results of critique
- [x] final concepts

**Comment by 0Arkadias0** [comment]
![Image](https://user-images.githubusercontent.com/79337715/210112756-2e2b831f-4f2f-4b3d-b2a3-596e08cfb934.jpg)



![Image](https://user-images.githubusercontent.com/79337715/210112805-3fbb40bd-ba0f-4dd3-a47c-45c00144f60e.jpg)
