### ISSUE TITLE
Review Preston's Forest area layout

### ISSUE THREAD

**Issue by alyg563** [AztecGameLab/LongTermGame7#38]
![Image](https://user-images.githubusercontent.com/43483413/210285180-f956a1d1-41fb-479c-ae8f-889a1331beaf.png)

Use this doc as a guide for what Story has decided will be in the Forest area: https://docs.google.com/document/d/1smrfas4Ccge5J0zwzhO9iusZUxjcH68TiXIVuaFm5vY/edit?usp=sharing

**Comment by alyg563** [comment]
![Image](https://user-images.githubusercontent.com/43483413/210285094-30030b04-0dca-42a3-bd67-24249a14d5aa.png)

**Comment by chmilk1** [comment]
[CamScanner_01-06-2023_17.19.pdf](https://github.com/AztecGameLab/LongTermGame7/files/10365428/CamScanner_01-06-2023_17.19.pdf)

**Comment by alyg563** [comment]
Looks fantastic!
