### ISSUE TITLE
Design the Forest arenas (3)

### ISSUE THREAD

**Issue by alyg563** [AztecGameLab/LongTermGame7#41]
I'll have u start on the Forest arenas so if you put obstacles in the arena for the creatures to move around, make sure they make sense for a forest. We are going to want the arenas to be of a similar size with obstacles, interactable items that could be useful in combat, and you can have different elevations for the terrain.

Keep in mind that these arenas will be a part of a pool that is randomly selected when a fight starts and that the Forest is the first area a player will traverse through.

James and I were thinking that at first we could make blueprints of our designs on "paper" and then after we review your work, you can move into implementation. Let me know if you have any questions!

**Comment by Halter24** [comment]
![Image](https://user-images.githubusercontent.com/109498346/216725165-40e71fcc-df92-4fb5-8ed1-162648c80f4a.jpeg)
![Image](https://user-images.githubusercontent.com/109498346/216725166-9007acf3-1691-4f83-9ec1-9e69e0c220e9.jpeg)
![Image](https://user-images.githubusercontent.com/109498346/216725167-08823573-8bea-4e13-80a8-3b2ca1d2a61f.jpeg)

**Comment by Halter24** [comment]
Flowers, both the movement and increased attack one, can be randomly placed in any 3 of these maps since they more or less fit in all of them.

**Comment by alyg563** [comment]
I recommend maybe adding more trees to the first arena with strategically placed bridges. Looks good though!

**Comment by whatAreYouD0ingStepBr0** [comment]
Tree Battle - If a player is attacked and knocked back they fall off the tree and into water below. Only way back up is to take a vine back up spending all the player's action points.
