### ISSUE TITLE
Design the Hills arenas (3)

### ISSUE THREAD

**Issue by alyg563** [AztecGameLab/LongTermGame7#42]
I'll have u start on the Hills arenas so if you put obstacles in the arena for the creatures to move around, make sure they make sense for a hilly green area. We are going to want the arenas to be of a similar size with obstacles, interactable items that could be useful in combat, and you can have different elevations for the terrain.

Keep in mind that these arenas will be a part of a pool that is randomly selected when a fight starts and that the Hills is the second area a player will traverse through.

James and I were thinking that at first we could make blueprints of our designs on "paper" and then after we review your work, you can move into implementation. Let me know if you have any questions!

**Comment by dominic-griffith** [comment]
![Image](https://user-images.githubusercontent.com/65990043/215238329-e2114c1e-edea-479c-ae98-44b86a7b8a3b.png)

Ideas for Items on map: (1) Dynamite - used for damage or destruction (2) Flag - give temporary increased movement range



![Image](https://user-images.githubusercontent.com/65990043/215238343-2213d569-e9d2-4e40-b731-6edb8c23c409.png)

Ideas for Items on map: (1) Rock - summons rock pet to fight with you (2) Phone - calls in train when used



![Image](https://user-images.githubusercontent.com/65990043/215238359-7927106d-bfa5-4a78-b19c-ccd671ccc8e5.png)

Ideas for Items on map: (1) Grapes - eat to heal self (2) Rope - make into either (2.1) Lasso - to prevent enemy movement or (2.2) Voodoo doll - inflict pain on enemy

**Comment by Halter24** [comment]
Vineyard's cool for the last map - if the map needs to get shrunk or stuff gets taken out i recommend keeping that part

**Comment by alyg563** [comment]
I think the scale of these arenas is too big. Think the size of the AGL room or a little bigger as the standard size. I think the train should be a mine cart system instead. The cell phone tower is also out of place time-wise. Finally, I like the top but not the hot air balloon because of scale. Everything else looks really good though and I think these designs are good to move to the implementation stage.
