### ISSUE TITLE
Design the Laboratory arenas (3)

### ISSUE THREAD

**Issue by alyg563** [AztecGameLab/LongTermGame7#43]
You are designing the Lab arenas so if you put obstacles in the arena for the creatures to move around, make sure they make sense for a laboratory. We are going to want the arenas to be of a similar size with obstacles, interactable items that could be useful in combat, and you can have different elevations for the terrain.

Keep in mind that these arenas will be a part of a pool that is randomly selected when a fight starts and that the Forest is the first area a player will traverse through.

James and I were thinking that at first we could make blueprints of our designs on "paper" and then after we review your work, you can move into implementation. Let me know if you have any questions!

**Comment by ratmonky** [comment]
[Lab Arenas Concept #1.pdf](https://github.com/AztecGameLab/LongTermGame7/files/10583162/Lab.Arenas.Concept.1.pdf)

Concept for Lab Arenas.

**Comment by alyg563** [comment]
I like everything!
